name: 'Deploy Azure Infrastructure'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TERRAFORM_WORKING_DIR: './terraform'
 
jobs:
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out so runner has access to .tf
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log into Azure using Service Principal credentials in GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Install Terraform on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      # Step 4: Run 'terraform init' to prepare working dir
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      # Step 5: Run 'terraform plan' to create an execution plan.
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform_plan
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve # Automatically approve the plan
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
    
  deploy_function_app:
    name: 'Deploy Function App Code'
    runs-on: ubuntu-latest
    needs: terraform_apply

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./src/real-time-ingestion

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'func-dl-ingestion'
          package: './src/real-time-ingestion'
